name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - uses: actions/checkout@v4

      # 2️⃣ Setup Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4️⃣ Install Playwright browsers (Chromium, Firefox, WebKit)
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # 5️⃣ Run Playwright tests (WebKit project only)
      - name: Run WebKit tests
        run: npx playwright test --project=webkit --reporter=line

      # 6️⃣ Upload HTML and Allure reports
      - name: Upload Playwright HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-html-report
          path: playwright-pom-demo/reports/html-report/
          retention-days: 30

      - name: Upload Playwright Allure report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-allure-report
          path: playwright-pom-demo/reports/allure-results/
          retention-days: 30
